src/main/scala/nl.knaw.dans.easy.validatebag/rules/ProfileVersion0.scala, src/main/scala/nl.knaw.dans.easy.validatebag/rules/metadata/package.scala, src/test/resources/bags/filesxml-default-namespace-child/bag-info.txt, src/test/resources/bags/filesxml-default-namespace-child/bagit.txt, src/test/resources/bags/filesxml-default-namespace-child/manifest-md5.txt, src/test/resources/bags/filesxml-default-namespace-child/metadata/dataset.xml, src/test/resources/bags/filesxml-default-namespace-child/metadata/files.xml, src/test/resources/bags/filesxml-default-namespace-child/tagmanifest-md5.txt, src/test/resources/bags/filesxml-invalid-dct-child/bag-info.txt, src/test/resources/bags/filesxml-invalid-dct-child/bagit.txt, src/test/resources/bags/filesxml-invalid-dct-child/manifest-md5.txt, src/test/resources/bags/filesxml-invalid-dct-child/metadata/dataset.xml, src/test/resources/bags/filesxml-invalid-dct-child/metadata/files.xml, src/test/resources/bags/filesxml-invalid-dct-child/tagmanifest-md5.txt, src/test/resources/bags/filesxml-invalid-default-namespace-child/bag-info.txt, src/test/resources/bags/filesxml-invalid-default-namespace-child/bagit.txt, src/test/resources/bags/filesxml-invalid-default-namespace-child/manifest-md5.txt, src/test/resources/bags/filesxml-invalid-default-namespace-child/metadata/dataset.xml, src/test/resources/bags/filesxml-invalid-default-namespace-child/metadata/files.xml, src/test/resources/bags/filesxml-invalid-default-namespace-child/tagmanifest-md5.txt, src/test/scala/nl.knaw.dans.easy.validatebag/rules/metadata/MetadataRulesSpec.scala
Fixes EASY-1586
* add default namespace and dc-namespace to allowed namespaces for `files.xml`, besides dcterms-namespace
* add/fix tests
=> EASY-1586: easy-validate-dans-bag rejects ALL non-dcterms in files.xml

src/main/scala/nl.knaw.dans.easy.validatebag/EasyValidateDansBagApp.scala, src/main/scala/nl.knaw.dans.easy.validatebag/rules/ProfileVersion0.scala, src/main/scala/nl.knaw.dans.easy.validatebag/rules/ProfileVersion1.scala, src/test/scala/nl.knaw.dans.easy.validatebag/rules/profile/NumberedRulesSpec.scala
Fixes EASY-1588
* solve the problem of duplicate rule numbers by specifying separate requirements in one rule
* test that there are no duplicate rule numbers
* test that all referred rule numbers exist
=> EASY-1588: Make all rule numbers unique

src/main/scala/nl.knaw.dans.easy.validatebag/rules/metadata/package.scala
Based on the messages I see in the latest tests by PAN, I decided to do some slight improvements on the error message that is outputted by easy-validate-dans-bag.
* the code was very hard to read, so I extracted some values
* I closed the `(` starting with `only in bag`
* the diffs now have `{...}` around them. That way it also looks better when indicating an empty diff set
* I removed the `\n` at the end of `msg2`. That way we don't have extra newlines at the end of the message in our CSV
=> Improve error message

pom.xml, src/main/scala/nl.knaw.dans.easy.validatebag/EasyValidateDansBagApp.scala, src/main/scala/nl.knaw.dans.easy.validatebag/EasyValidateDansBagServlet.scala, src/main/scala/nl.knaw.dans.easy.validatebag/ResultMessage.scala, src/main/scala/nl.knaw.dans.easy.validatebag/rules/bagit/package.scala, src/test/resources/bags/valid-bag/bag-info.txt, src/test/resources/bags/valid-bag/bagit.txt, src/test/resources/bags/valid-bag/data/sine-md5.txt, src/test/resources/bags/valid-bag/data/sub/sub/sine-md5.txt, src/test/resources/bags/valid-bag/manifest-md5.txt, src/test/resources/bags/valid-bag/manifest-sha1.txt, src/test/resources/bags/valid-bag/metadata/dataset.xml, src/test/resources/bags/valid-bag/metadata/files.xml, src/test/resources/bags/valid-bag/tagmanifest-md5.txt, src/test/resources/logback.xml, src/test/scala/nl.knaw.dans.easy.validatebag/EasyValidateDansBagServletSpec.scala, src/test/scala/nl.knaw.dans.easy.validatebag/ServletFixture.scala, src/test/scala/nl.knaw.dans.easy.validatebag/TestSupportFixture.scala, src/test/scala/nl.knaw.dans.easy.validatebag/XmlValidatorSpec.scala
Fixes EASY-1775-add-more-logging
* now log which bag is being validated  [uuid / directory name]
* and if it was successful
* or why not
validate bags and see if the validation process gets logged
=> EASY-1775 Log when a bag is being validated and whether it is a success or why not

src/main/assembly/dist/install/easy-validate-dans-bag.service
Fixes EASY-1823
* add status=143 as success code
Where should the reviewer @DANS-KNAW/easy start?
=> EASY-1823: add status=143 as success code

pom.xml, src/main/assembly/dist/cfg/logback-service.xml
Reverts DANS-KNAW/easy-validate-dans-bag#45
@DANS-KNAW/easy
=> EASY-1826: Revert "EASY-1826 add a journal log appender"

pom.xml, src/main/scala/nl.knaw.dans.easy.validatebag/EasyValidateDansBagServlet.scala
Fixes EASY-1981
* add servlet logging
=> EASY-1981: add servlet logging

src/main/scala/nl.knaw.dans.easy.validatebag/EasyValidateDansBagApp.scala, src/main/scala/nl.knaw.dans.easy.validatebag/EasyValidateDansBagServlet.scala, src/test/scala/nl.knaw.dans.easy.validatebag/EasyValidateDansBagServletSpec.scala
Fixes EASY-2002
* EASY-2002 add version to baseurl response
=> EASY-2002: add version to baseurl response

pom.xml, src/test/resources/bags/bag with spaces/bag-info.txt, src/test/resources/bags/bag with spaces/bagit.txt, src/test/resources/bags/bag with spaces/data/sine-md5.txt, src/test/resources/bags/bag with spaces/data/sub/sub/sine-md5.txt, src/test/resources/bags/bag with spaces/manifest-md5.txt, src/test/resources/bags/bag with spaces/manifest-sha1.txt, src/test/resources/bags/bag with spaces/metadata/dataset.xml, src/test/resources/bags/bag with spaces/metadata/files.xml, src/test/resources/bags/bag with spaces/tagmanifest-md5.txt, src/test/scala/nl.knaw.dans.easy.validatebag/EasyValidateDansBagServletSpec.scala
Fixes EASY-2014
* add test with spaces in bag name
Related to https://github.com/DANS-KNAW/easy-ingest-flow/pull/107
=> EASY-2014: add test with spaces in bag name

src/main/scala/nl.knaw.dans.easy.validatebag/rules/sequence/package.scala
* improve error message and code readability for Is-Version-Of validation
* (basically, the code was hardly readable, so I improved that and then I saw that string interpolation wasn't done for one of the error messages)
=> improve error message and code readability for Is-Version-Of validation

src/main/scala/nl.knaw.dans.easy.validatebag/rules/ProfileVersion0.scala, src/test/resources/bags/files-in-wrong-metadata-dir/bag-info.txt, src/test/resources/bags/files-in-wrong-metadata-dir/bagit.txt, src/test/resources/bags/files-in-wrong-metadata-dir/data/sine-md5.txt, src/test/resources/bags/files-in-wrong-metadata-dir/data/sub/sub/sine-md5.txt, src/test/resources/bags/files-in-wrong-metadata-dir/manifest-md5.txt, src/test/resources/bags/files-in-wrong-metadata-dir/manifest-sha1.txt, src/test/resources/bags/files-in-wrong-metadata-dir/metadata/agreements.xml, src/test/resources/bags/files-in-wrong-metadata-dir/metadata/dataset.xml, src/test/resources/bags/files-in-wrong-metadata-dir/metadata/files.xml, src/test/resources/bags/files-in-wrong-metadata-dir/metadata/message-from-depositor.txt, src/test/resources/bags/files-in-wrong-metadata-dir/tagmanifest-md5.txt, src/test/resources/bags/valid-bag/metadata/depositor-info/agreements.xml, src/test/resources/bags/valid-bag/metadata/depositor-info/message-from-depositor.txt, src/test/scala/nl.knaw.dans.easy.validatebag/EasyValidateDansBagServletSpec.scala, src/test/scala/nl.knaw.dans.easy.validatebag/TestSupportFixture.scala
Fixes EASY-2085
* allow the directory depositor-info and children to be put in the metadata folder.
easy-deposit-api                      | [PR#145](https://github.com/DANS-KNAW/easy-deposit-api/pull/145)     | ..
=> EASY-2085: update validator to allow the directory depositor-info

src/main/scala/nl.knaw.dans.easy.validatebag/rules/metadata/package.scala, src/main/scala/nl.knaw.dans.easy.validatebag/rules/package.scala, src/main/scala/nl.knaw.dans.easy.validatebag/rules/sequence/package.scala, src/main/scala/nl.knaw.dans.easy.validatebag/rules/structural/package.scala, src/test/resources/bags/baginfo-with-is-version-of-invalid-scheme/bag-info.txt, src/test/resources/bags/baginfo-with-is-version-of-invalid-scheme/bagit.txt, src/test/resources/bags/baginfo-with-is-version-of-invalid-scheme/manifest-md5.txt, src/test/resources/bags/baginfo-with-is-version-of-invalid-scheme/tagmanifest-md5.txt, src/test/resources/bags/baginfo-with-is-version-of-invalid-uuid/bag-info.txt, src/test/resources/bags/baginfo-with-is-version-of-invalid-uuid/bagit.txt, src/test/resources/bags/baginfo-with-is-version-of-invalid-uuid/manifest-md5.txt, src/test/resources/bags/baginfo-with-is-version-of-invalid-uuid/tagmanifest-md5.txt, src/test/resources/bags/baginfo-with-is-version-of-without-urn/bag-info.txt, src/test/resources/bags/baginfo-with-is-version-of-without-urn/bagit.txt, src/test/resources/bags/baginfo-with-is-version-of-without-urn/manifest-md5.txt, src/test/resources/bags/baginfo-with-is-version-of-without-urn/tagmanifest-md5.txt, src/test/scala/nl.knaw.dans.easy.validatebag/TestSupportFixture.scala, src/test/scala/nl.knaw.dans.easy.validatebag/rules/RulesSpec.scala, src/test/scala/nl.knaw.dans.easy.validatebag/rules/metadata/MetadataRulesSpec.scala, src/test/scala/nl.knaw.dans.easy.validatebag/rules/sequence/SequenceRulesSpec.scala, src/test/scala/nl.knaw.dans.easy.validatebag/rules/structural/StructuralRulesSpec.scala
Fixes EASY-2094
- return a 200 but not compliant if is-version-of in valid
- return a 500 if we somehow give an absolute path to a numbered rule check.
=> Easy 2094 - invalid is-version-of should not return a bad request

src/main/assembly/dist/cfg/application.properties
Fixes EASY-
* allow to ingest deposits submitted with the ui
* 
* 
=> NO JIRA ISSUE: increment version of agreements.xsd

src/main/scala/nl.knaw.dans.easy.validatebag/rules/ProfileVersion0.scala, src/main/scala/nl.knaw.dans.easy.validatebag/rules/metadata/package.scala, src/test/resources/bags/filesxml-invalid-access-rights/bag-info.txt, src/test/resources/bags/filesxml-invalid-access-rights/bagit.txt, src/test/resources/bags/filesxml-invalid-access-rights/manifest-md5.txt, src/test/resources/bags/filesxml-invalid-access-rights/metadata/dataset.xml, src/test/resources/bags/filesxml-invalid-access-rights/metadata/files.xml, src/test/resources/bags/filesxml-invalid-access-rights/tagmanifest-md5.txt, src/test/resources/bags/filesxml-valid-access-rights/bag-info.txt, src/test/resources/bags/filesxml-valid-access-rights/bagit.txt, src/test/resources/bags/filesxml-valid-access-rights/manifest-md5.txt, src/test/resources/bags/filesxml-valid-access-rights/metadata/dataset.xml, src/test/resources/bags/filesxml-valid-access-rights/metadata/files.xml, src/test/resources/bags/filesxml-valid-access-rights/tagmanifest-md5.txt, src/test/scala/nl.knaw.dans.easy.validatebag/rules/metadata/MetadataRulesSpec.scala
Fixes EASY-2029
* validate Access Rights in dct:accessRights element, accessibleToRights element and visibleToRights element
Make a bag with valid and invalid access rights elements and ingest them through Sword interface
(e.g../run.sh Simple http://deasy.dans.knaw.nl/sword2/collection/1 mendeltest mendeltest  src/main/resources/examples/invalid-acccess-rights)
=> EASY-2029 implementeer check op waarden dct:accessRights in files.xml

pom.xml
Fixes EASY-2209: upgrade easy-licenses
* 
* 
* 
https://github.com/DANS-KNAW/easy-deposit-agreement-creator/pull/59
=> EASY-2209: upgrade easy-licenses

README.md, src/main/assembly/bin.xml
Fixes EASY-2400
* Update documentation to be in line with other projects
* Remove references to outdated files from bin.xml
=> EASY-2400 Update documentation and bin.xml

src/main/scala/nl.knaw.dans.easy.validatebag/EasyValidateDansBagServlet.scala, src/main/scala/nl.knaw.dans.easy.validatebag/package.scala, src/test/scala/nl.knaw.dans.easy.validatebag/EasyValidateDansBagServletSpec.scala
Fixes EASY-2616
* catch an error in parsing the `InfoPackageType`
=> EASY-2616: catch error in parsing InfoPackageType

pom.xml, src/test/scala/nl.knaw.dans.easy.validatebag/CanConnectFixture.scala, src/test/scala/nl.knaw.dans.easy.validatebag/DebugConfigSpec.scala, src/test/scala/nl.knaw.dans.easy.validatebag/ReadmeSpec.scala, src/test/scala/nl.knaw.dans.easy.validatebag/TestSupportFixture.scala
fixes EASY-2179
* update parent POM version
* fix deprecation warnings
repo                       | PR                | Note
easy-                      | [PR#](PRlink)     |
=> EASY-2179: update scalatra

src/main/scala/nl.knaw.dans.easy.validatebag/rules/ProfileVersion0.scala, src/test/resources/bags/metadata-correct/bag-info.txt, src/test/resources/bags/metadata-correct/tagmanifest-md5.txt, src/test/resources/bags/metadata-extra-file/bag-info.txt, src/test/resources/bags/metadata-extra-file/tagmanifest-md5.txt, src/test/scala/nl.knaw.dans.easy.validatebag/rules/structural/StructuralRulesSpec.scala
Fixes EASY-2730
* Allow metadata/license.txt file
dans-bagit-profile                      | [PR#12](https://github.com/DANS-KNAW/dans-bagit-profile/pull/12)     | ..
=> EASY-2730: Allow metadata/license.txt file

src/main/scala/nl.knaw.dans.easy.validatebag/rules/ProfileVersion0.scala, src/test/resources/bags/metadata-with-original/bag-info.txt, src/test/resources/bags/metadata-with-original/bagit.txt, src/test/resources/bags/metadata-with-original/manifest-md5.txt, src/test/resources/bags/metadata-with-original/metadata/dataset.xml, src/test/resources/bags/metadata-with-original/metadata/files.xml, src/test/resources/bags/metadata-with-original/metadata/original/dataset.xml, src/test/resources/bags/metadata-with-original/metadata/original/files.xml, src/test/resources/bags/metadata-with-original/tagmanifest-md5.txt, src/test/scala/nl.knaw.dans.easy.validatebag/rules/structural/StructuralRulesSpec.scala
Fixes EASY-2770
* Allow orig dir in metadata dir
* 
* 
easy-validate-dans-bag                      | [PR#91](https://github.com/DANS-KNAW/easy-validate-dans-bag/pull/91)     | ..
=> EASY-2770: Allow orig dir in metadata dir

src/test/scala/nl.knaw.dans.easy.validatebag/EasyValidateDansBagServletSpec.scala, src/test/scala/nl.knaw.dans.easy.validatebag/rules/metadata/MetadataRulesSpec.scala
Fixes EASY-
* fixed compiler warning
* fixed assume that aborted the test suite when running offline
=> NO JIRA ISSUE: fixed assume problems

docs/index.md, src/main/scala/nl.knaw.dans.easy.validatebag/Command.scala, src/main/scala/nl.knaw.dans.easy.validatebag/CommandLineOptions.scala, src/test/scala/nl.knaw.dans.easy.validatebag/validation/BatchSpec.scala
Fixes DD-393 validate a directory with multiple bags
* 
* 
* 
=> DD-393 validate a directory with multiple bags

src/main/scala/nl.knaw.dans.easy.validatebag/rules/ProfileVersion0.scala
Fixes EASY-
* 
* 
* 
allows deployment of
https://github.com/DANS-KNAW/easy-convert-bag-to-deposit/pull/34
=> save provenance in a file

src/main/scala/nl.knaw.dans.easy.validatebag/rules/ProfileVersion0.scala
Fixes DD-389: allow pre-staged.csv
* 
* 
* 
=> DD-389: allow pre-staged.csv
