- .travis.yml
- src/main/scala/nl.knaw.dans.easy.validatebag/rules/metadata/package.scala
- src/test/resources/bags/filesxml-non-dct-child/bag-info.txt
- src/test/resources/bags/filesxml-non-dct-child/metadata/files.xml
- src/test/resources/bags/filesxml-non-dct-child/tagmanifest-md5.txt
- src/test/resources/bags/filesxml-non-file-element/bag-info.txt
- src/test/resources/bags/filesxml-non-file-element/metadata/files.xml
- src/test/resources/bags/filesxml-non-file-element/tagmanifest-md5.txt
- src/test/scala/nl.knaw.dans.easy.validatebag/rules/metadata/MetadataRulesSpec.scala
Fixes EASY-1603
* Implement the rules specified in https://github.com/DANS-KNAW/easy-specs/pull/53
@DANS-KNAW/easy for review.
> EASY-1603 Improved checks on files.xml in specs and easy-validate-dans-bag

- src/main/scala/nl.knaw.dans.easy.validatebag/EasyValidateDansBagApp.scala
- src/main/scala/nl.knaw.dans.easy.validatebag/rules/ProfileVersion0.scala
- src/main/scala/nl.knaw.dans.easy.validatebag/rules/bagit/package.scala
- src/main/scala/nl.knaw.dans.easy.validatebag/rules/package.scala
- src/main/scala/nl.knaw.dans.easy.validatebag/rules/structural/package.scala
- src/main/scala/nl.knaw.dans.easy.validatebag/validation/package.scala
- src/test/resources/bags/baginfo-added-empty-line/bag-info.txt
- src/test/resources/bags/baginfo-added-empty-line/bagit.txt
- src/test/resources/bags/baginfo-added-empty-line/manifest-md5.txt
- src/test/scala/nl.knaw.dans.easy.validatebag/rules/RulesSpec.scala
- src/test/scala/nl.knaw.dans.easy.validatebag/rules/bagit/BagInfoTxtRulesSpec.scala
- src/test/scala/nl.knaw.dans.easy.validatebag/rules/structural/StructuralRulesSpec.scala
- src/test/scala/nl.knaw.dans.easy.validatebag/validation/ValidationSpec.scala
Fixes EASY-1731
* Make sure that when unable to get the declared profile version because of a malformed `bag-info.txt` the default version `0` is used.
* Report a malformed `bag-info.txt`
* Not trigger a fatal error when a `bag-info.txt` is malformed, by skipping rules that try to read the bag.
* Fail fast when a fatal error is encountered, so that a clear exception is reported in the logs (contributed by @rvanheest).
* https://github.com/DANS-KNAW/easy-validate-dans-bag/compare/master...janvanmansum:EASY-1731?expand=1#diff-993c8fb41fa8a517f4d7ed0cfaa55897R88
* https://github.com/DANS-KNAW/easy-validate-dans-bag/compare/master...janvanmansum:EASY-1731?expand=1#diff-3df2b5375972cc5c0725c90193f7a3a4R118
For example by an example deposit with the sample bag from the issue.
> EASY-1731 easy-validate-dans-bag fails prematurely on malformed bag-info.txt

- src/main/scala/nl.knaw.dans.easy.validatebag/rules/ProfileVersion0.scala
- src/main/scala/nl.knaw.dans.easy.validatebag/rules/metadata/package.scala
- src/test/resources/bags/ddm-invalid-archis-identifiers/bag-info.txt
- src/test/resources/bags/ddm-invalid-archis-identifiers/bagit.txt
- src/test/resources/bags/ddm-invalid-archis-identifiers/manifest-md5.txt
- src/test/resources/bags/ddm-invalid-archis-identifiers/metadata/dataset.xml
- src/test/resources/bags/ddm-invalid-archis-identifiers/metadata/files.xml
- src/test/resources/bags/ddm-invalid-archis-identifiers/tagmanifest-md5.txt
- src/test/scala/nl.knaw.dans.easy.validatebag/rules/metadata/MetadataRulesSpec.scala
Fixes EASY-1732
* add the requirement from `easy-ddm` to the `dans-bagit-profile` (both versions) that states
> Any `dc:identifier` or `dcterms:identifier` element with `xsi:type="id-type:ARCHIS-ZAAK-IDENTIFICATIE` MUST have a value of 10 or less characters.
* https://github.com/DANS-KNAW/easy-specs/pull/58
> add dataset.xml requirement for identifier with id-type:ARCHIS-ZAAK-IDENTIFICATIE

- src/main/scala/nl.knaw.dans.easy.validatebag/rules/ProfileVersion0.scala
- src/main/scala/nl.knaw.dans.easy.validatebag/rules/metadata/package.scala
- src/test/resources/bags/ddm-correct-doi/bag-info.txt
- src/test/resources/bags/ddm-correct-doi/bagit.txt
- src/test/resources/bags/ddm-correct-doi/data/ruimtereis01_verklaring.txt
- src/test/resources/bags/ddm-correct-doi/data/secret.txt
- src/test/resources/bags/ddm-correct-doi/manifest-sha1.txt
- src/test/resources/bags/ddm-correct-doi/metadata/dataset.xml
- src/test/resources/bags/ddm-correct-doi/metadata/files.xml
- src/test/resources/bags/ddm-correct-doi/tagmanifest-sha1.txt
- src/test/resources/bags/ddm-incorrect-doi/bag-info.txt
- src/test/resources/bags/ddm-incorrect-doi/bagit.txt
- src/test/resources/bags/ddm-incorrect-doi/data/ruimtereis01_verklaring.txt
- src/test/resources/bags/ddm-incorrect-doi/data/secret.txt
- src/test/resources/bags/ddm-incorrect-doi/manifest-sha1.txt
- src/test/resources/bags/ddm-incorrect-doi/metadata/dataset.xml
- src/test/resources/bags/ddm-incorrect-doi/metadata/files.xml
- src/test/resources/bags/ddm-incorrect-doi/tagmanifest-sha1.txt
- src/test/resources/bags/ddm-missing-doi/bag-info.txt
- src/test/resources/bags/ddm-missing-doi/bagit.txt
- src/test/resources/bags/ddm-missing-doi/data/ruimtereis01_verklaring.txt
- src/test/resources/bags/ddm-missing-doi/data/secret.txt
- src/test/resources/bags/ddm-missing-doi/manifest-sha1.txt
- src/test/resources/bags/ddm-missing-doi/metadata/dataset.xml
- src/test/resources/bags/ddm-missing-doi/metadata/files.xml
- src/test/resources/bags/ddm-missing-doi/tagmanifest-sha1.txt
- src/test/scala/nl.knaw.dans.easy.validatebag/rules/metadata/MetadataRulesSpec.scala
Fixes EASY-1704
* check that for an AIP there is at last one DOI identifier defined in dataset.xml
* check that all DOIs are valid
* report invalid DOIs
Note: this is not yet implemented for ProfileVersion1 because all metadata checks are still missing.  We will make another issue to add all the metadata checks for version 1.
> EASY-1704 Implement rule dataset.xml must contain DOI (3.1.3)

- src/main/scala/nl.knaw.dans.easy.validatebag/rules/metadata/package.scala
~~Fixes EASY-~~
* only fail on the archis identifier rule when a violation is found
> only fail with archis identifier if actually something incorrect was found

- src/main/scala/nl.knaw.dans.easy.validatebag/rules/metadata/package.scala
- src/test/resources/bags/ddm-no-archis-identifiers/bag-info.txt
- src/test/resources/bags/ddm-no-archis-identifiers/bagit.txt
- src/test/resources/bags/ddm-no-archis-identifiers/manifest-md5.txt
- src/test/resources/bags/ddm-no-archis-identifiers/metadata/dataset.xml
- src/test/resources/bags/ddm-no-archis-identifiers/metadata/files.xml
- src/test/resources/bags/ddm-no-archis-identifiers/tagmanifest-md5.txt
- src/test/resources/bags/ddm-valid-archis-identifiers/bag-info.txt
- src/test/resources/bags/ddm-valid-archis-identifiers/bagit.txt
- src/test/resources/bags/ddm-valid-archis-identifiers/manifest-md5.txt
- src/test/resources/bags/ddm-valid-archis-identifiers/metadata/dataset.xml
- src/test/resources/bags/ddm-valid-archis-identifiers/metadata/files.xml
- src/test/resources/bags/ddm-valid-archis-identifiers/tagmanifest-md5.txt
- src/test/scala/nl.knaw.dans.easy.validatebag/rules/metadata/MetadataRulesSpec.scala
This is a follow-up on #40 in which I thought I fix the bug with incorrectly identified validation errors.
This time it was when a valid Archis identifier was present, it would still make the validation fail. In terms of code, it would result in a `validationResult = List(Success(()))`, which then got evaluated to not being an empty list.
https://github.com/DANS-KNAW/easy-validate-dans-bag/blob/fcf8cb0cbe7e1bc891d132b2407f3f19dfbf2979/src/main/scala/nl.knaw.dans.easy.validatebag/rules/metadata/package.scala#L271-L279
This got now fixed to first filtering out only the `Failure` instances in the array.
https://github.com/DANS-KNAW/easy-validate-dans-bag/blob/29e50831b0456cf3dcf5254d68fce6322e034cc0/src/main/scala/nl.knaw.dans.easy.validatebag/rules/metadata/package.scala#L271-L279
Also I …
> only fail with archis identifier if actually something incorrect was found (part 2)

- src/main/scala/nl.knaw.dans.easy.validatebag/XmlValidator.scala
- src/test/scala/nl.knaw.dans.easy.validatebag/XmlValidatorSpec.scala
Fixes EASY-
* have less code in the XMLValidator
* more unit tests
easy-validate-dans-bag/src/test/scala/nl.knaw.dans.easy.validatebag/XmlValidatorSpec.scala
upload some bags (both valid and invalid) and verify if the validation still works like it should
> EASY-1733 remove redundant xml-validator  code

- src/main/assembly/dist/cfg/application.properties
- src/test/resources/debug-config/application.properties
Fixes EASY-1820 : increment version of agreements.xsd due to rename (licenseAgrement -> depositAgrement)
* 
* 
* 
deploy together with:
* https://github.com/DANS-KNAW/easy-specs/pull/63
* https://github.com/DANS-KNAW/easy-deposit-api/pull/102
> EASY-1820 : increment version of agreements.xsd due to rename

- src/main/assembly/dist/bin/easy-validate-dans-bag
Fixes EASY-1670
* It is possible to pass parameters containing spaces
> EASY-1670 Command-line startup script: argumenten met spaties

- src/main/scala/nl.knaw.dans.easy.validatebag/rules/metadata/package.scala
- src/test/resources/bags/ddm-empty-multisurface/bag-info.txt
- src/test/resources/bags/ddm-empty-multisurface/bagit.txt
- src/test/resources/bags/ddm-empty-multisurface/data/ruimtereis01_verklaring.txt
- src/test/resources/bags/ddm-empty-multisurface/data/secret.txt
- src/test/resources/bags/ddm-empty-multisurface/manifest-sha1.txt
- src/test/resources/bags/ddm-empty-multisurface/metadata/dataset.xml
- src/test/resources/bags/ddm-empty-multisurface/metadata/files.xml
- src/test/resources/bags/ddm-empty-multisurface/tagmanifest-sha1.txt
- src/test/resources/bags/ddm-no-srs-names/bag-info.txt
- src/test/resources/bags/ddm-no-srs-names/bagit.txt
- src/test/resources/bags/ddm-no-srs-names/data/ruimtereis01_verklaring.txt
- src/test/resources/bags/ddm-no-srs-names/data/secret.txt
- src/test/resources/bags/ddm-no-srs-names/manifest-sha1.txt
- src/test/resources/bags/ddm-no-srs-names/metadata/dataset.xml
- src/test/resources/bags/ddm-no-srs-names/metadata/files.xml
- src/test/resources/bags/ddm-no-srs-names/tagmanifest-sha1.txt
- src/test/scala/nl.knaw.dans.easy.validatebag/rules/metadata/MetadataRulesSpec.scala
Fixes EASY-1882
* no longer return an error when a `MultiSurface` doesn't have any polygons
> EASY-1882: no error when a MultiSurface doesn't have any polygons

- src/main/scala/nl.knaw.dans.easy.validatebag/rules/ProfileVersion0.scala
Fixes EASY-1961
* you can add a message from the depositor (`message-from-depositor.txt`) in the `metadata` folder
ingest a test bag (with-depositor-message) that is attached to the JIRA issue (https://drivenbydata.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=EASY&modal=detail&selectedIssue=EASY-1961)
> EASY-1961 easy-validate-dans-bag moet message-from-depositor accepteren in v0

- pom.xml
- src/main/scala/nl.knaw.dans.easy.validatebag/EasyValidateDansBagServlet.scala
Fixes EASY-2056
* no longer use `.logResponse` to log the servlet response
* add `LogResponseBodyOnError` trait to servlet definition
> EASY-2056: use new servlet-logging features from dans-scala-lib v1.6.0

- pom.xml
- src/test/scala/nl.knaw.dans.easy.validatebag/EasyValidateDansBagServletSpec.scala
* replaces calls to `Guava UrlEscapers` methods with calls to `dans-scala-lib `encoding methods
(which in turn make use of `Guava PercentEscaper`)
easy-auth-info                 | [DANS-KNAW/easy-auth-info/pull/23] | ..
easy-bag-store                | [DANS-KNAW/easy-bag-store/pull/91] | ..
easy-download                | [DANS-KNAW/easy-download/pull/33] | ..
easy-ingest-flow             | [DANS-KNAW/easy-ingest-flow/pull/109] | ..
easy-solr4files-index      | [DANS-KNAW/easy-solr4files-index/pull/39] | ..
> EASY-2021 Corrigeer aanroepen van bag-store op nieuwe percent-encoding regels

- src/main/assembly/dist/cfg/licenses.txt
- src/main/scala/nl.knaw.dans.easy.validatebag/TargetBag.scala
- src/main/scala/nl.knaw.dans.easy.validatebag/rules/metadata/package.scala
- src/test/resources/bags/ddm-correct-license-uri-on-new-line/bag-info.txt
- src/test/resources/bags/ddm-correct-license-uri-on-new-line/bagit.txt
- src/test/resources/bags/ddm-correct-license-uri-on-new-line/manifest-md5.txt
- src/test/resources/bags/ddm-correct-license-uri-on-new-line/metadata/dataset.xml
- src/test/resources/bags/ddm-correct-license-uri-on-new-line/metadata/files.xml
- src/test/resources/bags/ddm-correct-license-uri-on-new-line/tagmanifest-md5.txt
- src/test/scala/nl.knaw.dans.easy.validatebag/rules/metadata/MetadataRulesSpec.scala
fixes EASY-2114
* correctly read XML (wrapped in `Utility.trim`)
* remove unnecessary `asInstanceOf` calls
* add return types to private methods
* add license 'DANS general conditions of use'
> EASY-2114: DANS license causes http500 in easy-validate-dans-bag

- src/main/assembly/dist/cfg/application.properties
- src/test/resources/debug-config/application.properties
Fixes EASY-2220
* fetch for validation versionless schema files `ddm.xsd`, `files.xsd` and `agreements.xsd`
> EASY-2220: maak ddm.xsd versieloos in validate-dans-bag

- pom.xml
upgrade easy-licenses from `v1.0.3` to `v1.0.4`
> upgrade easy-licenses to v1.0.4

- pom.xml
- src/main/scala/nl.knaw.dans.easy.validatebag/rules/sequence/package.scala
- src/test/scala/nl.knaw.dans.easy.validatebag/rules/sequence/SequenceRulesSpec.scala
Fixes EASY-2332
* validate `UUIDs` using `dans.lib.string.toUUID` method
easy-archive-bag   | [PR#66](https://github.com/DANS-KNAW/easy-archive-bag/pull/66)     | ..
easy-auth-info   | [PR#36](https://github.com/DANS-KNAW/easy-auth-info/pull/36)     | ..
easy-bag-index  | [PR#50](https://github.com/DANS-KNAW/easy-bag-index/pull/50)     | ..
easy-bag-store  | [PR#100](https://github.com/DANS-KNAW/easy-bag-store/pull/100)     | ..
easy-delete-dataset  | [PR#19](https://github.com/DANS-KNAW/easy-delete-dataset/pull/19)     | ..
easy-deposit-api  | [PR#204](https://github.com/DANS-KNAW/easy-deposit-api/pull/204)     | ..
easy-deposit-properties  | …
> EASY-2332: validation of UUIDs

- src/main/scala/nl.knaw.dans.easy.validatebag/rules/metadata/package.scala
- src/test/resources/bags/ddm-incorrect-urls/metadata/dataset.xml
- src/test/resources/bags/ddm-incorrect-urls/tagmanifest-sha1.txt
- src/test/scala/nl.knaw.dans.easy.validatebag/rules/metadata/MetadataRulesSpec.scala
Fixes EASY-2605
* validate also `DOIs` and `URNs` in `alternative identifier` (`scheme="id-type:DOI"` and `scheme="id-type:URNI"`)
> EASY-2605: "Alternative identifier" veld wordt niet gevalideerd

- src/main/scala/nl.knaw.dans.easy.validatebag/rules/metadata/package.scala
- src/test/resources/bags/ddm-correct-urls/metadata/dataset.xml
- src/test/resources/bags/ddm-correct-urls/tagmanifest-sha1.txt
~Fixes EASY-~
* exclude DOI XML bodies when a href body is provided
```xml
<ddm:references scheme="id-type:DOI">https://dx.doi.org/doi:10.17026/test-123-456</ddm:references>
<ddm:references scheme="id-type:DOI" href="https://dx.doi.org/doi:10.17026/test-123-456">a doi referencing my dataset</ddm:references>
```
For the first example, the body should be validated to be a correct DOI (URL).
For the second example, the body should NOT be validated, since an `href` is already present.
> NO-JIRA: exclude DOI XML bodies when a href body is provided

- src/main/scala/nl.knaw.dans.easy.validatebag/package.scala
- src/main/scala/nl.knaw.dans.easy.validatebag/rules/ProfileVersion0.scala
- src/main/scala/nl.knaw.dans.easy.validatebag/rules/metadata/package.scala
- src/test/scala/nl.knaw.dans.easy.validatebag/rules/metadata/MetadataRulesSpec.scala
Fixes EASY-2615 doi validation
* have the DOI rule split in two: presence and syntax
* 
* 
> EASY-2615: doi validation

- src/main/scala/nl.knaw.dans.easy.validatebag/rules/ProfileVersion0.scala
- src/main/scala/nl.knaw.dans.easy.validatebag/rules/ProfileVersion1.scala
- src/test/scala/nl.knaw.dans.easy.validatebag/EasyValidateDansBagServletSpec.scala
Fixes EASY-2689
* Only check for SHA-1 payload manifests in AIPs, not in SIPs
> EASY-2689: Make SHA-1 mandatory only for AIPs

- src/main/scala/nl.knaw.dans.easy.validatebag/rules/metadata/package.scala
- src/test/resources/bags/ddm-CC-0-license-but-no-rightsholder/bag-info.txt
- src/test/resources/bags/ddm-CC-0-license-but-no-rightsholder/bagit.txt
- src/test/resources/bags/ddm-CC-0-license-but-no-rightsholder/manifest-md5.txt
- src/test/resources/bags/ddm-CC-0-license-but-no-rightsholder/metadata/dataset.xml
- src/test/resources/bags/ddm-CC-0-license-but-no-rightsholder/metadata/files.xml
- src/test/resources/bags/ddm-CC-0-license-but-no-rightsholder/tagmanifest-md5.txt
- src/test/scala/nl.knaw.dans.easy.validatebag/rules/metadata/MetadataRulesSpec.scala
Fixes EASY-2729
* Make Rightsholder optional for CC0 licensed deposits
> EASY-2729: Make Rightsholder optional for CC0 licensed deposits

- src/main/scala/nl.knaw.dans.easy.validatebag/rules/ProfileVersion0.scala
- src/test/scala/nl.knaw.dans.easy.validatebag/rules/structural/StructuralRulesSpec.scala
Fixes EASY-2759
* add `license.html` to files that are allowed in `metadata` directory
> EASY-2759: license.html added to files that are allowed in metadata directory

- src/main/scala/nl.knaw.dans.easy.validatebag/rules/ProfileVersion0.scala
Fixes EASY-2775
* Make rule 4.2 an AIP-only check in easy-validate-dans-bag
> EASY-2775 Make rule 4.2 an AIP-only check in easy-validate-dans-bag

- .travis.yml
- pom.xml
- src/main/scala/nl.knaw.dans.easy.validatebag/rules/sequence/package.scala
DD-326
* Upgrade parent
* Refactor a bit of code that was not compatible with Java 11.
* Check that is compiles under both Java 11 and 8:
```
brew install brew install adoptopenjdk11
export JAVA_HOME=`/usr/libexec/java_home -v 11`
java -version
mvn clean install
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
java -version
mvn clean install
```
* Check that the refactored code still works. For this you would need to do an AIP-type check with an update-deposit to see that contains the same EASY-User-Account value as the bags in the sequence in bag-store that it updates.
* https://github.com/DANS-KNAW/dd-dtap/pull/70
> Upgraded parent to be compatible with Java 11

- pom.xml
- src/main/scala/nl.knaw.dans.easy.validatebag/rules/ProfileVersion0.scala
- src/main/scala/nl.knaw.dans.easy.validatebag/rules/metadata/package.scala
- src/test/resources/bags/metadata-pre-staged-csv-all-three-differ/bag-info.txt
- src/test/resources/bags/metadata-pre-staged-csv-all-three-differ/bagit.txt
- src/test/resources/bags/metadata-pre-staged-csv-all-three-differ/manifest-md5.txt
- src/test/resources/bags/metadata-pre-staged-csv-all-three-differ/metadata/dataset.xml
- src/test/resources/bags/metadata-pre-staged-csv-all-three-differ/metadata/files.xml
- src/test/resources/bags/metadata-pre-staged-csv-all-three-differ/metadata/pre-staged.csv
- src/test/resources/bags/metadata-pre-staged-csv-all-three-differ/tagmanifest-md5.txt
- src/test/resources/bags/metadata-pre-staged-csv-one-missing/bag-info.txt
- src/test/resources/bags/metadata-pre-staged-csv-one-missing/bagit.txt
- src/test/resources/bags/metadata-pre-staged-csv-one-missing/manifest-md5.txt
- src/test/resources/bags/metadata-pre-staged-csv-one-missing/metadata/dataset.xml
- src/test/resources/bags/metadata-pre-staged-csv-one-missing/metadata/files.xml
- src/test/resources/bags/metadata-pre-staged-csv-one-missing/metadata/pre-staged.csv
- src/test/resources/bags/metadata-pre-staged-csv-one-missing/tagmanifest-md5.txt
- src/test/resources/bags/metadata-pre-staged-csv/bag-info.txt
- src/test/resources/bags/metadata-pre-staged-csv/bagit.txt
- src/test/resources/bags/metadata-pre-staged-csv/manifest-md5.txt
- src/test/resources/bags/metadata-pre-staged-csv/metadata/dataset.xml
- src/test/resources/bags/metadata-pre-staged-csv/metadata/files.xml
- src/test/resources/bags/metadata-pre-staged-csv/metadata/pre-staged.csv
- src/test/resources/bags/metadata-pre-staged-csv/tagmanifest-md5.txt
- src/test/scala/nl.knaw.dans.easy.validatebag/rules/metadata/MetadataRulesSpec.scala
Fixes DD-539
* check that the filepaths in `filesXml` correspond to the `payload files` combined with filepaths in `pre-staged.csv`
> DD-539: files.xml items hetzij in de manifest, hetzij in pre-staged.csv

- src/main/scala/nl.knaw.dans.easy.validatebag/rules/ProfileVersion0.scala
- src/main/scala/nl.knaw.dans.easy.validatebag/rules/metadata/package.scala
- src/main/scala/nl.knaw.dans.easy.validatebag/rules/structural/package.scala
- src/test/scala/nl.knaw.dans.easy.validatebag/rules/metadata/MetadataRulesSpec.scala
Completes #108 
* 
* 
* build deploy on deasy
* copy `easy-validate-dans-bag/src/test/resources/bags/original-filepaths-non-valid-bag` to `dtap/easy-dtap/shared`
* on deasy `easy-validate-dans-bag /vagrant/shared/original-filepaths-non-valid-bag/`
* it fails with more messages than 
- [3.2.4b] 2 'filepath' attributes are not found in 'original-filepaths.txt' data/sub/sub/sine-md5.txt, data/sub/sub/vacio-or-so.txt.
> EASY-2846: PR on PR, compares files.xml paths with original-filepaths.txt
